CREATE DATABASE IF NOT EXISTS QLCongTacGV CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QLCongTacGV;

-- 1. CÁC BẢNG DANH MỤC ĐỘC LẬP (Tạo trước)
CREATE TABLE CHUCDANH (
    MACD CHAR(6) PRIMARY KEY,
    TENCD VARCHAR(100) CHARACTER SET utf8mb4,
    DONGIATIET INT -- VD: 100000, 130000
);

CREATE TABLE KHOA (
    MAKHOA CHAR(6) PRIMARY KEY,
    TENKHOA VARCHAR(100) CHARACTER SET utf8mb4
);

CREATE TABLE DONVIDAOTAO (
    MADONVI CHAR(6) PRIMARY KEY,
    TENDONVI VARCHAR(100) CHARACTER SET utf8mb4
);

CREATE TABLE HEDAOTAO (
    MAHE CHAR(6) PRIMARY KEY,
    TENHE VARCHAR(100) CHARACTER SET utf8mb4
);

CREATE TABLE HOCKY (
    MAHOCKY CHAR(6) PRIMARY KEY,
    TENHK VARCHAR(50) CHARACTER SET utf8mb4,
    NAMHOC VARCHAR(50),
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4
);

CREATE TABLE LOAIMONHOC (
    MALOAIMH CHAR(6) PRIMARY KEY,
    TENLOAIMH VARCHAR(100) CHARACTER SET utf8mb4,
    HESO FLOAT -- VD: Lý thuyết 1.0, Thực hành 0.8
);

CREATE TABLE LOAINGUOIDUNG (
    MaLoai CHAR(6) PRIMARY KEY,
    TenLoaiND VARCHAR(30) CHARACTER SET utf8mb4
);

CREATE TABLE PHONGHOC (
    MAPHONG CHAR(6) PRIMARY KEY,
    TENPHONG VARCHAR(100) CHARACTER SET utf8mb4,
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4
);

-- 2. CÁC BẢNG CÓ KHÓA NGOẠI MỨC 1
CREATE TABLE CANBOGIANGDAY (
    MSCB CHAR(6) PRIMARY KEY,
    HOTEN VARCHAR(100) CHARACTER SET utf8mb4,
    GIOITINH VARCHAR(10) CHARACTER SET utf8mb4,
    NGAYSINH DATE,
    QUEQUAN VARCHAR(150) CHARACTER SET utf8mb4,
    DIACHI VARCHAR(150) CHARACTER SET utf8mb4,
    SDT CHAR(12),
    EMAIL VARCHAR(100),
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4,
    MAKHOA CHAR(6),
    MACD CHAR(6),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
    FOREIGN KEY (MACD) REFERENCES CHUCDANH(MACD)
);

CREATE TABLE MONHOC (
    MAMH CHAR(6) PRIMARY KEY,
    TENMH VARCHAR(100) CHARACTER SET utf8mb4,
    SOTC INT,
    MALOAIMH CHAR(6),
    FOREIGN KEY (MALOAIMH) REFERENCES LOAIMONHOC(MALOAIMH)
);

-- 3. CÁC BẢNG CÓ KHÓA NGOẠI MỨC 2
CREATE TABLE NGUOIDUNG (
    MaND CHAR(6) PRIMARY KEY,
    MaLoai CHAR(6),
    TinhTrang VARCHAR(30) CHARACTER SET utf8mb4,
    MatKhau VARCHAR(30),
    FOREIGN KEY (MaND) REFERENCES CANBOGIANGDAY(MSCB),
    FOREIGN KEY (MaLoai) REFERENCES LOAINGUOIDUNG(MaLoai)
);

CREATE TABLE LOPCHUYENNGANH (
    MALOP CHAR(6) PRIMARY KEY,
    TENLOP VARCHAR(100) CHARACTER SET utf8mb4,
    NGANH VARCHAR(100) CHARACTER SET utf8mb4,
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4,
    MADONVI CHAR(6),
    MAHE CHAR(6),
    MSCB CHAR(6), -- Cố vấn học tập
    MAKHOA CHAR(6),
    SOLUONGSV INT,
    FOREIGN KEY (MSCB) REFERENCES CANBOGIANGDAY(MSCB),
    FOREIGN KEY (MADONVI) REFERENCES DONVIDAOTAO(MADONVI),
    FOREIGN KEY (MAHE) REFERENCES HEDAOTAO(MAHE),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- 4. CÁC BẢNG CÓ KHÓA NGOẠI MỨC 3
CREATE TABLE SINHVIEN (
    MSSV CHAR(6) PRIMARY KEY,
    TENSV VARCHAR(100) CHARACTER SET utf8mb4,
    GIOITINH VARCHAR(10) CHARACTER SET utf8mb4,
    NGAYSINH DATE,
    QUEQUAN VARCHAR(150) CHARACTER SET utf8mb4,
    DIACHI VARCHAR(150) CHARACTER SET utf8mb4,
    SDT CHAR(12),
    EMAIL VARCHAR(100),
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4,
    MALOP CHAR(6),
    FOREIGN KEY (MALOP) REFERENCES LOPCHUYENNGANH(MALOP)
);

CREATE TABLE LOPHOCPHAN (
    MALHP CHAR(6) PRIMARY KEY,
    TENLHP VARCHAR(100) CHARACTER SET utf8mb4,
    SISO INT,
    TINHTRANG VARCHAR(50) CHARACTER SET utf8mb4,
    MSCB CHAR(6),
    MAHOCKY CHAR(6),
    MALOP CHAR(6),
    MAMH CHAR(6),
    MAPHONG CHAR(6),
    NGAY DATE,
    FOREIGN KEY (MSCB) REFERENCES CANBOGIANGDAY(MSCB),
    FOREIGN KEY (MAHOCKY) REFERENCES HOCKY(MAHOCKY),
    FOREIGN KEY (MALOP) REFERENCES LOPCHUYENNGANH(MALOP),
    FOREIGN KEY (MAMH) REFERENCES MONHC(MAMH),
    FOREIGN KEY (MAPHONG) REFERENCES PHONGHOC(MAPHONG)
);

-- 5. CÁC BẢNG LIÊN QUAN ĐẾN THỜI GIAN VÀ TÍNH LUƠNG
CREATE TABLE THOIKHOABIEU (
    MATKB INT AUTO_INCREMENT PRIMARY KEY,
    MALHP CHAR(6),
    THU VARCHAR(50) CHARACTER SET utf8mb4,
    TIETBATDAU INT,
    TIETKETTHUC INT,
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    HESONGOAIGIO FLOAT DEFAULT 1.0,
    FOREIGN KEY (MALHP) REFERENCES LOPHOCPHAN(MALHP)
);

CREATE TABLE BANGLUONG (
    MABANGLUONG INT AUTO_INCREMENT PRIMARY KEY,
    MSCB CHAR(6),
    MAHOCKY CHAR(6),
    TONGTIEN DECIMAL(15,2),
    NGAYTAO DATE,
    FOREIGN KEY (MSCB) REFERENCES CANBOGIANGDAY(MSCB),
    FOREIGN KEY (MAHOCKY) REFERENCES HOCKY(MAHOCKY)
);